@startuml
!define RECTANGLE class

RECTANGLE "Client Application" as Client
RECTANGLE "VideoCompressor Interface" as Interface
RECTANGLE "VideoCompressorImpl" as Impl
RECTANGLE "FileManager" as FileManager
RECTANGLE "FFmpegWrapper" as FFmpeg
RECTANGLE "BinaryExtractor" as Extractor
RECTANGLE "PlatformDetector" as Platform

RECTANGLE "CompressionConfig" as Config
RECTANGLE "CompressionResult" as Result
RECTANGLE "CompressionType" as Type

RECTANGLE "VideoCompressionException" as BaseEx
RECTANGLE "UnsupportedFormatException" as FormatEx
RECTANGLE "FFmpegExecutionException" as ExecEx

Client --> Interface
Interface --> Impl
Impl --> FileManager
Impl --> FFmpeg
FFmpeg --> Extractor
Extractor --> Platform

Impl --> Config
Impl --> Result
Config --> Type

Impl --> BaseEx
BaseEx --> FormatEx
BaseEx --> ExecEx
@enduml
